export var rawData = [
	{
		id: 1,
		proTitle: "This is protitle 1 ",
		title: "This is title 1 ",
		subtitle: "This is sub title 1 ",
		content:
			"This is content for the card 1This is content for the card 1This is content for the card 1This is content for the card 1This is content for the card 1",
		learn_more: "learn more",
	},
	{
		proTitle: "This is protitle  2",
		title: "This is title 2",
		subtitle: "This is sub title 2",
		id: 2,
		content: "This is content for the card 2",
		learn_more: "learn more 2",
	},
	{
		id: 3,
		title: "This is title 3",
		subtitle: "This is sub title 3",
		proTitle: "This is protitle 3",
		content: "This is content for the card 3",
		learn_more: "learn more 3",
	},
	{
		id: 4,
		proTitle: "This is protitle  4",
		title: "This is title 4",
		subtitle: "This is sub title 4",
		content: "This is content for the card 4",
		learn_more: "learn more 4",
	},
	{
		id: 5,
		proTitle: "This is protitle 1 ",
		title: "This is title 1 ",
		subtitle: "This is sub title 1 ",
		content:
			"This is content for the card 1This is content for the card 1This is content for the card 1This is content for the card 1This is content for the card 1",
		learn_more: "learn more",
	},
	{
		id: 6,
		proTitle: "This is protitle  2",
		title: "This is title 2",
		subtitle: "This is sub title 2",
		content: "This is content for the card 2",
		learn_more: "learn more 2",
	},
	{
		id: 7,
		proTitle: "This is protitle 3",
		title: "This is title 3",
		subtitle: "This is sub title 3",
		content: "This is content for the card 3",
		learn_more: "learn more 3",
	},
	{
		proTitle: "This is protitle  4",
		id: 8,
		title: "This is title 4",
		subtitle: "This is sub title 4",
		content: "This is content for the card 4",
		learn_more: "learn more 4",
	},
	{
		id: 9,
		proTitle: "This is protitle 1 ",
		title: "This is title 1 ",
		subtitle: "This is sub title 1 ",
		content:
			"This is content for the card 1This is content for the card 1This is content for the card 1This is content for the card 1This is content for the card 1",
		learn_more: "learn more",
	},
	{
		proTitle: "This is protitle  2",
		id: 10,
		title: "This is title 2",
		subtitle: "This is sub title 2",
		content: "This is content for the card 2",
		learn_more: "learn more 2",
	},
	{
		proTitle: "This is protitle 3",
		id: 11,
		title: "This is title 3",
		subtitle: "This is sub title 3",
		content: "This is content for the card 3",
		learn_more: "learn more 3",
	},
	{
		id: 12,
		proTitle: "This is protitle  4",
		title: "This is title 4",
		subtitle: "This is sub title 4",
		content: "This is content for the card 4",
		learn_more: "learn more 4",
	},
	{
		proTitle: "This is protitle 1 ",
		id: 13,
		title: "This is title 1 ",
		subtitle: "This is sub title 1 ",
		content:
			"This is content for the card 1This is content for the card 1This is content for the card 1This is content for the card 1This is content for the card 1",
		learn_more: "learn more",
	},
	{
		proTitle: "This is protitle  2",
		title: "This is title 2",
		id: 14,
		subtitle: "This is sub title 2",
		content: "This is content for the card 2",
		learn_more: "learn more 2",
	},
	{
		proTitle: "This is protitle 3",
		title: "This is title 3",
		id: 15,
		subtitle: "This is sub title 3",
		content: "This is content for the card 3",
		learn_more: "learn more 3",
	},
	{
		proTitle: "This is protitle  4",
		title: "This is title 4",
		id: 16,
		subtitle: "This is sub title 4",
		content: "This is content for the card 4",
		learn_more: "learn more 4",
	},
];
